### DISCUSSION TITLE
Functions with "type": "rest" type produce (type: 'Action')/r/nDetails:/r/nSystem.Net.Http.HttpRequestException: Cannot assign requested address (localhost:5296)

### DISCUSSION THREAD

**Discussion by Kounavi** [serverlessworkflow/synapse#360] [Q&A] [answered]
Hello.
I am trying to run this workflow:

```json
{
  "id": "invoke-services-async",
  "name": "Invoke Services Async",
  "version": "0.1.13",
  "specVersion": "0.8",
  "functions": [
    {
      "name": "Invoke Send Email Function",
      "operation": "http://localhost:5296/swagger/v1/swagger.json#customer",
      "type": "rest"
    }
  ],
  "states": [
    {
      "name": "Send Email",
      "type": "operation",
      "actions": [
        {
          "name": "Invoke Send Email Action",
          "functionRef": {
            "refName": "Invoke Send Email Function",
            "arguments": {
              "customer": "${ .customer }"
            }
          }
        }
      ],
      "end": true
    }
  ]
}
```

I have a ASP .NET Core REST API (OpenAPI compatible) that reads and exposes this JSON via a GET:

```json
{
    "customer": {
        "name": "Iraklis",
        "surname": "D.",
        "from": "i.d@email.com",
        "to": ["s.k@email.com", "f.k@example.com"],
        "cc": ["n.u@email.com"],
        "subject": "Hello everyone :)",
        "body": ["This is a test email", "", "--", "Kind regards,", "Iraklis D."]
    }
}
```

Service runs on http://localhost:5296

However, every time I try and run the workflow the workflow is in a faulted state with this output:

```json
{
  "code": "HttpRequest",
  "message": "Cannot assign requested address (localhost:5296)"
}
```

Logs show this:

```log
Sending HTTP request GET http://localhost:5295/swagger/v1/swagger.json
[14:38:24] warning: Synapse.Worker.Services.Processors.OpenApiFunctionProcessor[0]
An error occured while executing the activity '5ec6dd91-7e37-41cc-8b6c-d8a04f502362' (type: 'Action')/r/nDetails:/r/nSystem.Net.Http.HttpRequestException: Cannot assign requested address (localhost:5296)
---> System.Net.Sockets.SocketException (99): Cannot assign requested address
```

What am I doing wrong?

I have made certain that the function URL contains the proper **operation id** based on my swagger.json but the error seems unrelated.
Any ideas? Is this a k8s thing and I need to expose a port or something? Something else?

My swagger.json is as follows:
```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "WorkflowEmail",
    "version": "1.0"
  },
  "paths": {
    "/api/Email/Customer": {
      "get": {
        "tags": [
          "Email"
        ],
        "operationId": "customer",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/Email"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Email"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/Email"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Customer": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "nullable": true
          },
          "surname": {
            "type": "string",
            "nullable": true
          },
          "from": {
            "type": "string",
            "nullable": true
          },
          "to": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "nullable": true
          },
          "cc": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "nullable": true
          },
          "subject": {
            "type": "string",
            "nullable": true
          },
          "body": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "Email": {
        "type": "object",
        "properties": {
          "customer": {
            "$ref": "#/components/schemas/Customer"
          }
        },
        "additionalProperties": false
      },
      "ProblemDetails": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "nullable": true
          },
          "title": {
            "type": "string",
            "nullable": true
          },
          "status": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "detail": {
            "type": "string",
            "nullable": true
          },
          "instance": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": { }
      }
    }
  }
}
````

Any kind of assistance, suggestion and / or indication would be very much appreciated! 😄

**Comment by cdavernas** [comment]
Hey @Kounavi!
Your problem is indeed related to K8s and/or Docker, that reserve the localhost hostname. 
You should replace localhost in your operation definition by the pod/service name of your API, allowing Synapse to contact your service using the k8s DNS from within the cluster.
Hope this helps!

```json
...
 "functions": [
    {
      "name": "Invoke Send Email Function",
      "operation": "http://myapi/swagger/v1/swagger.json#customer",
      "type": "rest"
    }
  ]
...
```

**Reply by Kounavi** [reply]
Hey @cdavernas. Thank you for your prompt response! I appreciate this a lot :)

Just a slight clarifications that this API runs on localhost but outside the localhost kubernetes environment. 
Other than that, I will try and search in order how to do this but do you have a guide on how to do this?
I was looking at [Synapse Documentation](https://github.com/serverlessworkflow/specification/tree/main) but I could not find anything about this :/

**Reply by cdavernas** [reply]
You are very welcome!

There's not really any doc on that, as this is rather a system configuration issue. 

You can however fix that in at least three, not so convenient ways. 

The first one is to edit your system's host file. In windows environment, that means editing your etc file and adding a new non localhost dns pointing at your loopback interface.

The second is to use a reverse proxy, such as Nginx or Traefik, to hide your API behind a non-localhost DNS.

The third, and certainly the easiest one, is to add your API to your K8S deployment, if possible, and proceed with the intra cluster DNS.

Hope this helps 😉!

**Reply by cdavernas** [reply]
You can find additional ways to do so in the following post: https://stackoverflow.com/questions/65123401/how-to-access-hosts-localhost-from-inside-kubernetes-cluster

**Reply by Kounavi** [reply]
Yeah I tried that one but I am still not able to make it  work though 😓 (I also replaced `host.docker.internal` with `kubernetes.docker.internal`)

**Reply by Kounavi** [reply]
@cdavernas 
This is what I have added in Synapse's deployment YAML (the **_stand-alone.yaml_** file)

```yaml
---

kind: Service
apiVersion: v1
metadata:
  name: synapse-ingress-service
  namespace: synapse
  labels: 
    app: synapse-ingress-service
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  ports:
    - name: http-ingress
      port: 5296
      targetPort: 5296
  type: ExternalName
  externalName: kubernetes.docker.internal
  selector:
    app: synapse

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: synapse
  labels: 
    app: synapse-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  ingressClassName: traefik
  rules:
    - host: localhost
      http:
        paths:
          - path: /api/Email/Customer
            pathType: Exact
            backend:
              service:
                name: synapse-ingress-service
                port:
                  number: 5296
          - path: /swagger/v1/swagger.json
            pathType: Exact
            backend:
              service:
                name: synapse-ingress-service
                port:
                  number: 5296

---
```

FYI, we use Rancher Desktop for Kubernetes deployments which means it uses the traefik controller as an ingress class. Docker (desktop) uses Rancher's Kubernetes as context where applicable.  Ports 42286 (Synapse Web UI) and 41387 (I don't know what that is yet) are being port forwarded to identical ports.

**Reply by cdavernas** [reply]
I'm on PTO until tomorrow, I'll have a look as soon as I'm back and will share my deployments if that helps!

That being said, port 41387 is the HTTP/2 on which the GRPC runtime API  is hosted, which is used by runner containers to update activities and workflows.

**Reply by Kounavi** [reply]
@cdavernas Apologies. Enjoy your PTO and please let me know when you can at your earliest convenience! :)

**Reply by Kounavi** [reply]
Hey @cdavernas. Do you have any deployments to share? 😄

**Reply by Kounavi** [reply, marked as answer]
@cdavernas So, it seems that for Kubernetes you need to provide the POD's exact IP address rather than localhost as localhost is tied to 127.0.0.1 which would effectively prevent traffic to the pod unless the correct combination of IP+port is used. I guess I could try binding PODs to 0.0.0.0 but I would have to research and figure how to do this. In the meantime I have solved my issue.
Now I am getting another error regarding my JSON file but it is irrelevant to this issue.

If you would like me to contribute in providing YAML files for development scenarios please let me know.
Happy to share these! :)

**Reply by cdavernas** [reply]
Yeah indeed! If you use Docker or K8s runtime, localhost will be the container/pod's loopback interface. 
On another note, instead of IP addresses, you should imho prefer using the targeted service/container name.

**Reply by Kounavi** [reply]
@cdavernas Yeah, possibly I should follow your advice. I will have a further look into these but I was finally able to invoke a service and get back the response using the POD's IP and port:

````yaml
{
  "id": "invoke-services-async",
  "name": "Invoke Services Async",
  "version": "0.1.13",
  "specVersion": "0.8",
  "functions": [
    {
      "name": "Invoke Send Email Function",
      "operation": "http://POD_IP:32296/swagger/v1/swagger.json#customer",
      "type": "rest"
    }
  ],
  "states": [
    {
      "name": "Send Email",
      "type": "operation",
      "actions": [
        {
          "name": "Invoke Send Email Action",
          "functionRef": {
            "refName": "Invoke Send Email Function",
            "arguments": {
              "customer": "${ .customer }"
            }
          }
        }
      ],
      "end": true
    }
  ]
}
```

The above one worked like a charm and got back the expected response. So awesome! 😄
