### DISCUSSION TITLE
Event handling on -> one

### DISCUSSION THREAD

**Discussion by alvin** [serverlessworkflow/synapse#415] [Q&A]
I have two test workflows, designed for me to test + understand  Synapse's internal event handling:

- The first, when run, creates an event (with static data)
- The second is meant to POST an external URL when the event from the first workflow occurs

```
document:
  dsl: 1.0.0-alpha2
  namespace: default
  name: generate-order-event
  version: 0.1.0
do:
- emitOrderEvent:
    emit:
      event:
        with:
          source: https://petstore.com
          type: com.petstore.order.placed.v1
          data: Big Dog
```

My issue is that I the 2nd one (below) doesn't trigger POST to webhook.site -- EXCEPT if I manually create a `post-order-from-event` instance (which isn't how this is supposed to work, right?).  Is my syntax wrong (I tried as JSON too so I know it is valid in a "mechanical" sense)...   Or do I have the wrong idea about what is supposed to happen with "schedule -> on" ?  I read all the docs I could find and that's what I think it's supposed to do... 

```
document:
  dsl: 1.0.0-alpha2
  namespace: default
  name: post-order-from-event
  version: 0.1.0
schedule:
  "on":
    one:
      with:
        type: com.petstore.order.placed.v1
do:
  - postTheOrderRemotely:
      call: http
      with:
        method: post
        endpoint: https://webhook.site/1f523c5c-7e89-40db-aef4-12b056235311
        body:
          data: something happened
```

**Comment by alvin** [comment]
can confirm that even the verbatim example for "Emit" also does not pass the front-end JSON validation that was just committed, so perhaps there is presently some issue with my syntax vs. what the server needs to see? 

```
document:
  dsl: '1.0.0-alpha2'
  namespace: test
  name: emit-example
  version: '0.1.0'
do:
  - emitEvent:
      emit:
        event:
          with:
            source: https://petstore.com
            type: com.petstore.order.placed.v1
            data:
              client:
                firstName: Cruella
                lastName: de Vil
              items:
                - breed: dalmatian
                  quantity: 101
```

Validation:

```
Invalid definition

The workflow definition is not valid.
:

/document:

/do:

/document/dsl:

/document/namespace:

/document/name:

/document/version:

/do/0:

/do/0/emitEvent:

    oneOf: Expected 1 matching subschema but found 0
    oneOf: Expected 1 matching subschema but found 0
    required: Required properties ["do"] are not present
    required: Required properties ["fork"] are not present
    required: Required properties ["for","do"] are not present
    required: Required properties ["listen"] are not present
    required: Required properties ["raise"] are not present
    required: Required properties ["run"] are not present
    required: Required properties ["set"] are not present
    required: Required properties ["switch"] are not present
    required: Required properties ["try","catch"] are not present
    required: Required properties ["wait"] are not present
    required: Required properties ["call","with"] are not present
    required: Required properties ["call","with"] are not present
    required: Required properties ["call","with"] are not present
    required: Required properties ["call","with"] are not present
    required: Required properties ["call"] are not present

/do/0/emitEvent/emit:

    : All values fail against the false schema
    : All values fail against the false schema
    : All values fail against the false schema
    : All values fail against the false schema
    : All values fail against the false schema
    : All values fail against the false schema
    : All values fail against the false schema
    : All values fail against the false schema
    : All values fail against the false schema
    : All values fail against the false schema
    : All values fail against the false schema
    : All values fail against the false schema
    : All values fail against the false schema
    : All values fail against the false schema
    : All values fail against the false schema
    : All values fail against the false schema

/do/0/emitEvent/emit/event:

    required: Required properties ["source","type"] are not present

/do/0/emitEvent/emit/event/with:

```

**Reply by cdavernas** [reply]
> Or do I have the wrong idea about what is supposed to happen with "schedule -> on" ?

Looks you got it right! The second flow should start upon consuming the order placed event.

You should see a correlation created, with a start/create outcome.

**Comment by cdavernas** [comment]
Does it work if you skip the `with`?
Like:
```yaml
emit:
  event:
    type: ....
    source: ....
```

It looks like the example you are using is invalid 😞
Do you mind reporting it (at the airport, so a bit challenging for me at the time being 🤣)?

When in doubt, check the `dsl-reference.md`, which should be correct.
