### DISCUSSION TITLE
Help: How do I trigger workflows using events

### DISCUSSION THREAD

**Discussion by oEscal** [serverlessworkflow/synapse#504] [Q&A] [answered]
As the title says, I don't understand how I can trigger a workflow or a set of tasks from a specific event. From the Synapse architecture, I noticed that the Correlator entity performs event processing into CloudEvents. However, how do I link a specific source of events with this Correlator?
I am very new to this project, and I have already tried to find this issue in the wiki and the repo's issues. However, I could not find what I was looking for.

**Comment by cdavernas** [comment, marked as answer]
Hi @oEscal! You are on the right track: (cloud)events need to be posted using the [structured JSON format](https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#32-structured-content-mode) on a correlator's API, at `/api/v1/events/pub`. This will trigger any matching correlation that exist, which you can view on the dashboard's dedicated interface.

**Reply by oEscal** [reply]
Thank you for your prompt response, @cdavernas! Could you direct me to the documentation on the correlator's API?

**Reply by cdavernas** [reply]
@oEscal You're very welcome!
As for the correlator's API documentation, I just realized it's not in the wiki. 

You can, however, consult the Swagger by launching a correlator and navigating to `/api/doc`.

**Comment by oEscal** [comment]
I am very sorry @cdavernas, but I continue to have multiple issues.

First, is Synapse supposed to automatically create a correlation when I define a schedule based on events in a workflow? I have the following workflow (just for me to get things started in Synapse):
```
document:
  dsl: 1.0.0-alpha5
  namespace: default
  name: new-workflow2
  version: 0.1.4
schedule:
  "on":
    one:
      with:
        type: com.petstore.order.placed.v1
do:
- function-a:
    call: http
    with:
      method: get
      endpoint: http://function-a.simple-conditional.svc.cluster.local?value=true
    output:
      schema:
        format: json
        document:
          type: object
          properties:
            result:
              type: bool
          required:
          - result
      as:
        result: ${ .result }
- decide:
    switch:
    - case-true:
        when: .result == true
        then: function-b
    - case-false:
        when: .result == false
        then: function-c
- function-b:
    do:
    - function:
        call: http
        with:
          method: get
          endpoint: http://function-b.simple-conditional.svc.cluster.local
    then: exit
- function-c:
    do:
    - function:
        call: http
        with:
          method: get
          endpoint: http://function-c.simple-conditional.svc.cluster.local
```
But no correlation is created (at least, I don't see any in the Web UI)

Second, when I post a new event with this type in the correlator API endpoint we discussed, nothing happens.
