### ISSUE TITLE
Arguments of an OpenAPI function reference are not bound to body

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/synapse#153]
**What happened**:

When referencing an `OpenAPI` function, specified arguments are not implicitly bound to the body

**What you expected to happen**:

Using latest `OpenAPI` versions, schema of the data to send is defined by the `OpenAPIFormat` object, and should be used to map the parameters implicitly

**How to reproduce it**:

Given an hypothetic function definition referencing an HTTP  POST operation:

```yaml
functions:
- name: OpenApiFunction
  operation: openapi.json#login
```

The following will fail:

```yaml
actions:
- name: TestFunction
  functionRef:
    refName: OpenApiFunction
    arguments:
      username: foo
      password: bar
```

But the following will work:

```yaml
actions:
- name: TestFunction
  functionRef:
    refName: OpenApiFunction
    arguments:
      body:                              #explicitly binding to the body, which is not great
        username: foo
        password: bar
```
