### ISSUE TITLE
The OpenApiFunctionProcessor fails to parse runtime expression based operation uris

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/synapse#163]
**What happened**:

Runtime expressions set as the `operation` property of a function definition of type OpenAPI are not properly evaluated

**What you expected to happen**:

Evaluate runtime expressions set as the `operation` property 

**How to reproduce it**:

Define then invoke an OpenAPI function such as the following:

```yaml
...
functions:
- name: Test
  type: rest
  operation: ${ runtimeExpression }
...
```

The workflow will fail because the url will result in the defined runtime expression instead of being evaluated

**Anything else we need to know?**:

Using composite values (expression + constant) will however work as expected:

```yaml
- name: Test
  type: rest
  operation: '${ runtimeExpression }/pathToOpenApi#operation'
```
