### ISSUE TITLE
ForEach states return the output collection instead of merging it with their input data

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/synapse#180]
**What happened**:

ForEach states return the output collection instead of merging it with their input data.

**What you expected to happen**:

ForEach states to return the output collection merged back into the state data.

**How to reproduce it**:

Create a ForEach state, such as:

```yaml
id: foreach
name: foreach
version: 1.0.0
specVersion: '0.8'
expressionLang: jq
functions:
- name: check-pet-status
  operation: https://petstore.swagger.io/v2/swagger.json#getPetById
  type: rest
states:
- name: Initialize pets
  type: inject
  data:
    pets:
    - id: 1
    - id: 2
    - id: 3
  transition: Check pets statuses
- name: Check pets statuses 
  type: foreach 
  iterationParam: pet
  inputCollection: ".pets"
  outputCollection: ".processedPets"
  actions:
  - functionRef:
      refName: check-pet-status
      arguments:
        petId: "${ .pet.id }"
    name: CheckPetStatus
  end: true
```

The state's output will be something like:

```json
[{
  "id": 1,
  "category": {
    "id": 1,
    "name": "string"
  },
  "name": "string",
  "photoUrls": [
    "string"
  ],
  "tags": [
    {
      "id": 1,
      "name": "string"
    }
  ],
  "status": "string"
},
{
  "id": 1,
  "category": {
    "id": 1,
    "name": "string"
  },
  "name": "string",
  "photoUrls": [
    "string"
  ],
  "tags": [
    {
      "id": 1,
      "name": "string"
    }
  ],
  "status": "string"
},
{
  "id": 1,
  "category": {
    "id": 1,
    "name": "string"
  },
  "name": "string",
  "photoUrls": [
    "string"
  ],
  "tags": [
    {
      "id": 1,
      "name": "string"
    }
  ],
  "status": "string"
}]
```

Instead of:

```json
{
  "pets":[{
    "id": 1
  },
  {
    "id": 2,
  },
  {
    "id": 3,
  }],
  "processedPets": [{
  "id": 1,
  "category": {
    "id": 1,
    "name": "string"
  },
  "name": "string",
  "photoUrls": [
    "string"
  ],
  "tags": [
    {
      "id": 1,
      "name": "string"
    }
  ],
  "status": "string"
},
{
  "id": 2
  "category": {
    "id": 1,
    "name": "string"
  },
  "name": "string",
  "photoUrls": [
    "string"
  ],
  "tags": [
    {
      "id": 1,
      "name": "string"
    }
  ],
  "status": "string"
},
{
  "id": 3,
  "category": {
    "id": 1,
    "name": "string"
  },
  "name": "string",
  "photoUrls": [
    "string"
  ],
  "tags": [
    {
      "id": 1,
      "name": "string"
    }
  ],
  "status": "string"
}]
}
```
