### ISSUE TITLE
Cannot save a workflow after an unsuccessfull save attempt

### ISSUE THREAD

**Issue by cdavernas** [serverlessworkflow/synapse#275]
**What happened**:

Cannot save a workflow after an unsuccessfull save attempt in the editor

**What you expected to happen**:

The workflow to be saved after errors have been fixed

**How to reproduce it**:

1. Create a workflow such as the following, which references a non existing external definitions (i.e. `functions`)
2. Try saving the workflow => an exception will be thrown because of a 404 NOT FOUND (i.e. `https://test.com/path_that_does_not_exist`)
3. Fix the `functions` by using an uri that returns an actual function definition collections
4. Save => nothing happens (no error, no console logs: nothing)

```yaml
id: breaks-editor-save
name: Breaks editor save feature
version: 1.0.0
specVersion: 0.8
functions: https://test.com/path_that_does_not_exist
states:
  - name: CallToExternalFunction
    type: operation
    actions:
      - name: callToExternalFunction
        functionRef:
          refName: get-pet-by-id
    end: true
```

**Environment**:

Main branch at https://github.com/neuroglia-io/synapse
