### ISSUE TITLE
Cannot make persistence work

### ISSUE THREAD

**Issue by whuanle** [serverlessworkflow/synapse#324]
synapse cannot save data.
Whether there are plans to support the storage of workflow definitions and processes to the database.

**Comment by cdavernas** [comment]
Synapse can save data! We are using it successfully in staging in multiple environments. You have an issue we are looking into (probably misconfiguration), but we have a lot on our plates right now.

**Comment by cdavernas** [comment]
I guess related to https://github.com/serverlessworkflow/specification/issues/713

**Comment by cdavernas** [comment]
In the meanwhile, please make sure you are using the latest images and plug-ins, using digests to be sure, as a couple of serialization issues were introduced and resolved with last version

**Comment by cdavernas** [comment]
@whuanle Please edit the issue by providing system info and logs of the error(s).
I know you provided more details in the other issue you created, but that was in the spec's repo and, even though I linked it, it's a better practice for newcomers potentially facing the same problems ;)

**Comment by raycch** [comment]
Hello, same problem with https://github.com/serverlessworkflow/specification/issues/713 here running on k8s linux x64 nodes, any ideas?
```YAML
apiVersion: v1
kind: Namespace
metadata:
  name: synapse

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: synapse
  namespace: synapse
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse
  namespace: synapse
  annotations:
    traffic.sidecar.istio.io/excludeOutboundIPRanges: 10.96.0.1/32
spec:
  selector:
    matchLabels:
      app: synapse
  template:
    metadata:
      labels:
        app: synapse
        version: '0.1.3'
      annotations:
        traffic.sidecar.istio.io/excludeOutboundIPRanges: 10.96.0.1/32
    spec:
      serviceAccountName: synapse
      containers:
      - name: synapse
        image: ghcr.io/serverlessworkflow/synapse@sha256:4d5803af0f98d45e230701ee5e2b422faae4e5d6d31e357db87e9d72e978d283
        imagePullPolicy: IfNotPresent
        env:
          - name: KUBERNETES_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
                
---

apiVersion: v1
kind: Service
metadata:
  name: synapse
  namespace: synapse
  labels: 
    app: synapse
spec:
  ports:
    - name: http
      port: 42286
      protocol: TCP
    - name: http-2
      port: 41387
      protocol: TCP 
  selector:
    app: synapse
    
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-manager
  namespace: synapse
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: synapse
  namespace: synapse
subjects:
  - kind: ServiceAccount
    name: synapse
    apiGroup: ""
roleRef:
  kind: Role
  name: pod-manager
  apiGroup: rbac.authorization.k8s.io
```
**workflow**
```YAML
id: greeting
name: Greeting Workflow
description: Greet Someone
version: 1.0.0
specVersion: '0.8'
functions:
  - name: greetingFunction
    operation: https://petstore.swagger.io/v2/swagger.json#loginUser
    type: rest
start: Greet
states:
  - name: Greet
    type: operation
    actions:
      - actionDataFilter:
          results: '${ {code: .code} }'
        functionRef:
          refName: greetingFunction
          arguments:
            username: ${ .username }
            password: ${ .password }
    end: true
```
**worker log**

[03:49:44] info: Synapse.Worker.Services.WorkflowRuntimeContext[0]
      Initializing the runtime context for workflow instance with id 'greeting-tanjgviuz0idoaglqomtja'...
[03:49:44] info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
[03:49:44] info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
[03:49:44] info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
[03:49:45] info: Synapse.Worker.Services.WorkflowRuntimeContext[0]
      Retrieving definition of workflow with id 'greeting:1.0.0'...
[03:49:46] info: Synapse.Worker.Services.WorkflowRuntimeContext[0]
      Runtime context initialized
[03:49:46] info: Synapse.Worker.Services.WorkflowRuntime[0]
      Starting the workflow's execution...
[03:49:46] info: Synapse.Worker.Services.Processors.OperationStateProcessor[0]
      Initializing activity '0930a32e-3076-49ee-b79e-fa23837d6e97' (type: 'State')...
[03:49:46] fail: Synapse.Worker.Services.WorkflowActivityProcessorFactory[0]
      An error occured while creating a new processor for the activity with id 'f9002234-3369-417b-9a92-4a27d7a7e7de': System.NullReferenceException: Failed to find an action that matches the metadata specified by the activity with id 'f9002234-3369-417b-9a92-4a27d7a7e7de'
         at Synapse.Worker.Services.WorkflowActivityProcessorFactory.CreateActionActivityProcessor(StateDefinition state, V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessorFactory.cs:line 125
         at Synapse.Worker.Services.WorkflowActivityProcessorFactory.Create(V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessorFactory.cs:line 72
[03:49:46] warn: Synapse.Worker.Services.Processors.OperationStateProcessor[0]
      An error occured while executing the activity '0930a32e-3076-49ee-b79e-fa23837d6e97' (type: 'State')/r/nDetails:/r/nSystem.NullReferenceException: Failed to find an action that matches the metadata specified by the activity with id 'f9002234-3369-417b-9a92-4a27d7a7e7de'
         at Synapse.Worker.Services.WorkflowActivityProcessorFactory.CreateActionActivityProcessor(StateDefinition state, V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessorFactory.cs:line 125
         at Synapse.Worker.Services.WorkflowActivityProcessorFactory.Create(V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessorFactory.cs:line 72
         at Synapse.Worker.Services.WorkflowActivityProcessorFactory.Synapse.Worker.Services.IWorkflowActivityProcessorFactory.Create(V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessorFactory.cs:line 320
         at Synapse.Worker.Services.WorkflowActivityProcessor.CreateProcessorFor(V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessor.cs:line 196
         at Synapse.Worker.Services.Processors.OperationStateProcessor.CreateProcessorFor(V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/Processors/OperationStateProcessor.cs:line 50
         at Synapse.Worker.Services.Processors.OperationStateProcessor.StartAsync() in /src/src/apps/Synapse.Worker/Services/Processors/OperationStateProcessor.cs:line 107
         at Synapse.Worker.Services.Processors.OperationStateProcessor.InitializeAsync(CancellationToken cancellationToken) in /src/src/apps/Synapse.Worker/Services/Processors/OperationStateProcessor.cs:line 64
         at Synapse.Worker.Services.WorkflowActivityProcessor.<>c__DisplayClass30_0.<<Synapse-Worker-Services-IWorkflowActivityProcessor-ProcessAsync>b__0>d.MoveNext() in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessor.cs:line 105
[03:49:46] warn: Synapse.Worker.Services.WorkflowRuntime[0]
      An error occured while executing the workflow instance: System.NullReferenceException: Failed to find an action that matches the metadata specified by the activity with id 'f9002234-3369-417b-9a92-4a27d7a7e7de'
         at Synapse.Worker.Services.WorkflowActivityProcessorFactory.CreateActionActivityProcessor(StateDefinition state, V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessorFactory.cs:line 125
         at Synapse.Worker.Services.WorkflowActivityProcessorFactory.Create(V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessorFactory.cs:line 72
         at Synapse.Worker.Services.WorkflowActivityProcessorFactory.Synapse.Worker.Services.IWorkflowActivityProcessorFactory.Create(V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessorFactory.cs:line 320
         at Synapse.Worker.Services.WorkflowActivityProcessor.CreateProcessorFor(V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessor.cs:line 196
         at Synapse.Worker.Services.Processors.OperationStateProcessor.CreateProcessorFor(V1WorkflowActivity activity) in /src/src/apps/Synapse.Worker/Services/Processors/OperationStateProcessor.cs:line 50
         at Synapse.Worker.Services.Processors.OperationStateProcessor.StartAsync() in /src/src/apps/Synapse.Worker/Services/Processors/OperationStateProcessor.cs:line 107
         at Synapse.Worker.Services.Processors.OperationStateProcessor.InitializeAsync(CancellationToken cancellationToken) in /src/src/apps/Synapse.Worker/Services/Processors/OperationStateProcessor.cs:line 64
         at Synapse.Worker.Services.WorkflowActivityProcessor.<>c__DisplayClass30_0.<<Synapse-Worker-Services-IWorkflowActivityProcessor-ProcessAsync>b__0>d.MoveNext() in /src/src/apps/Synapse.Worker/Services/WorkflowActivityProcessor.cs:line 105
[03:49:46] info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
