### ISSUE TITLE
Inconsistent context in for task

### ISSUE THREAD

**Issue by JBBianchi** [serverlessworkflow/synapse#373]
**What happened**:
When using `export.as` in a for loop, the context seems to be reset at each iteration.

(Note: accessing the context in `output.as` also seems to yield undesired results)

**What you expected to happen**:
The context to be consistent and passed to each iteration one after the other.

**How to reproduce it**:
##### Arrange
- Create a new workflow
```yaml
document:
  dsl: 1.0.0
  namespace: default
  name: star-wars
  version: 0.1.1
input:
  schema:
    format: json
    document:
      type: object
      properties:
        name:
          type: string
      required:
      - name
      additionalProperties: false
do:
- getCharacter:
    call: http
    with:
      method: get
      endpoint:
        uri: https://swapi.dev/api/people/?search={name}
    output:
      as: .results[0]
- getHomeworld:
    call: http
    with:
      method: get
      endpoint:
        uri: '{homeworld}'
- getNeighbours:
    for:
      each: resident
      in: .residents
    do:
    - getResident:
        call: http
        with:
          method: get
          endpoint:
            uri: ${ $resident }
        export:
          as:
            results: ${ $context.results + [$output] }
    output:
      as: ${ $context.results }
```
##### Act
- start the workflow with:
```yaml
name: leia
```

##### Assert
The context should be
```yaml
results:
- name: Leia Organa
  height: "150"
  mass: "49"
  hairColor: brown
  skinColor: light
  eyeColor: brown
  birthYear: 19BBY
  gender: female
  homeworld: https://swapi.dev/api/planets/2/
  films:
  - https://swapi.dev/api/films/1/
  - https://swapi.dev/api/films/2/
  - https://swapi.dev/api/films/3/
  - https://swapi.dev/api/films/6/
  species: []
  vehicles:
  - https://swapi.dev/api/vehicles/30/
  starships: []
  created: 2014-12-10T15:20:09.791000Z
  edited: 2014-12-20T21:17:50.315000Z
  url: https://swapi.dev/api/people/5/
- name: Bail Prestor Organa
  height: "191"
  mass: unknown
  hairColor: black
  skinColor: tan
  eyeColor: brown
  birthYear: 67BBY
  gender: male
  homeworld: https://swapi.dev/api/planets/2/
  films:
  - https://swapi.dev/api/films/5/
  - https://swapi.dev/api/films/6/
  species:
  - https://swapi.dev/api/species/1/
  vehicles: []
  starships: []
  created: 2014-12-20T16:53:08.575000Z
  edited: 2014-12-20T21:17:50.463000Z
  url: https://swapi.dev/api/people/68/
- name: Raymus Antilles
  height: "188"
  mass: "79"
  hairColor: brown
  skinColor: light
  eyeColor: brown
  birthYear: unknown
  gender: male
  homeworld: https://swapi.dev/api/planets/2/
  films:
  - https://swapi.dev/api/films/1/
  - https://swapi.dev/api/films/6/
  species: []
  vehicles: []
  starships: []
  created: 2014-12-20T19:49:35.583000Z
  edited: 2014-12-20T21:17:50.493000Z
  url: https://swapi.dev/api/people/81/
```

But instead, it is (only the last item):
```yaml
results:
- name: Raymus Antilles
  height: "188"
  mass: "79"
  hairColor: brown
  skinColor: light
  eyeColor: brown
  birthYear: unknown
  gender: male
  homeworld: https://swapi.dev/api/planets/2/
  films:
  - https://swapi.dev/api/films/1/
  - https://swapi.dev/api/films/6/
  species: []
  vehicles: []
  starships: []
  created: 2014-12-20T19:49:35.583000Z
  edited: 2014-12-20T21:17:50.493000Z
  url: https://swapi.dev/api/people/81/
```

And the output should be (according to the erroneous context):
```yaml
- name: Raymus Antilles
  height: "188"
  mass: "79"
  hairColor: brown
  skinColor: light
  eyeColor: brown
  birthYear: unknown
  gender: male
  homeworld: https://swapi.dev/api/planets/2/
  films:
  - https://swapi.dev/api/films/1/
  - https://swapi.dev/api/films/6/
  species: []
  vehicles: []
  starships: []
  created: 2014-12-20T19:49:35.583000Z
  edited: 2014-12-20T21:17:50.493000Z
  url: https://swapi.dev/api/people/81/
```

But instead, it is:
```yaml
{}
```

**Anything else we need to know?**:
An alternative version of the workflow would be that yield the expected result would be:
```yaml
document:
  dsl: 1.0.0
  namespace: default
  name: star-wars
  version: 0.1.0
input:
  schema:
    format: json
    document:
      type: object
      properties:
        name:
          type: string
      required:
      - name
      additionalProperties: false
do:
- getCharacter:
    call: http
    with:
      method: get
      endpoint:
        uri: https://swapi.dev/api/people/?search={name}
    output:
      as: .results[0]
- getHomeworld:
    call: http
    with:
      method: get
      endpoint:
        uri: '{homeworld}'
- getNeighbours:
    for:
      each: resident
      in: .residents
    do:
    - getResident:
        call: http
        with:
          method: get
          endpoint:
            uri: ${ $resident }
        output:
          as:
            results: ${ $input.results + [$output] }
    output:
      as: ${.results}
```
