### ISSUE TITLE
Validation Error The Certificates field is required when creating a new Operator

### ISSUE THREAD

**Issue by bvandewe** [serverlessworkflow/synapse#382]
**What happened**:

Trying to add a new Operator (with a tagged runner' image) results in HTTP 400, with no log on the api/backend:

Request `POST http://localhost:8080/api/v1/operators`

```yaml
apiVersion: synapse.io/v1
kind: Operator
metadata:
  name: new-operator
spec:
  runner:
    api:
      uri: http://api:8080
  runtime:
    container:
      image: "ghcr.io/serverlessworkflow/synapse/runner:1.0.0-alpha1"
```

Response: 

```json
{
    "type": "https://tools.ietf.org/html/rfc9110#section-15.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "errors": {
        "Spec.Runner.Certificates": [
            "The Certificates field is required."
        ]
    },
    "traceId": "00-ca0789d040dc17aa1e71757c8d354151-6f1ea4fd4f4443ea-00"
}
```

**What you expected to happen**:

If a certificate field is required, then it'd be great to show it on the UI somehow or include it transparently when posting the request if user isnt supposed to add it on the Operator' definition.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**: Docker Desktop v4.34.0
