### ISSUE TITLE
Iteration doesnt work when there is one item in the list

### ISSUE THREAD

**Issue by anushapai23** [serverlessworkflow/synapse#462]
**What happened**:
Iteration does not work as expected when there is one item in the list. 

**How to reproduce it**:
This is the portion of the workflow-

```
do:
- initialize:
    do:
    - resolveDefaultEnvironment:
        call: resolve-environment:1.0.0@default
        with:
          param1: ${ abc }
        export:
          as: '$workflow.input + { var: . }'
    - iterateOnPackage:
        for:
          each: environment
          in: $workflow.input.packages
        do:
        - setTest:
            set:
              test: value
            export:
              as: $context + .
```
It does not iterate when there is single element as shown below:
```
packages:
- ABC
```

Does run well with :
```
packages:
- ABC
- DEF
```
