### ISSUE TITLE
Flow entering infinite loop while using wait task

### ISSUE THREAD

**Issue by SonaThaj** [serverlessworkflow/synapse#485]
### I tried this:

Called 2 wait tasks one after the other with the same wait duration.

### This happened:

The workflow entered an infinite loop.

### I expected this:

After the second wait task, flow should have proceeded normally, without entering infinite loop.

### Is there a workaround?

If the wait duration is not the same, then infinite loop can be avoided. For eg, if the first wait task is waiting for 3s, then the second wait task duration should **not** be 3s.

### Anything else?

**Test code:**
```
document:
  dsl: 1.0.0-alpha5
  namespace: default
  name: test-wait
  version: 0.1.4
do:
- dummyset-1:
    set:
      test-1: hello
- wait-1:
    wait:
      seconds: 3
- dummyset-2:
    set:
      test-2: hello
- wait-2:
    wait:
      seconds: 3
- dummyset-3:
    set:
      test-3: hello
```
Instance:

<img width="691" alt="Image" src="https://github.com/user-attachments/assets/264a2517-2753-427d-86fa-548d92587c84" />

### Platform(s)

Windows

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.name: Bug Report 🐞
