### ISSUE TITLE
Scripts are not awaited by default

### ISSUE THREAD

**Issue by toxik** [serverlessworkflow/synapse#487]
### I tried this:

The script tasks don't wait until completion

```
document:
  dsl: 1.0.0-alpha5
  namespace: default
  name: scripts
  version: 0.1.32
do:
- log:
    run:
      script:
        language: js
        code: >
          console.log('hello world'); setTimeout(() => console.log('it waited for a bit!'))
      await: true
```

### This happened:

The script task is fire and forget.

### Is there a workaround?

changing to `await: false` seem to wait for the script to complete

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.name: Bug Report 🐞
