### ISSUE TITLE
Unable to fetch input data from events while a workflow is trigerred by an event

### ISSUE THREAD

**Issue by anushapai23** [serverlessworkflow/synapse#498]
### I tried this:

This is the workflow def:

```
document:
  dsl: 1.0.0-alpha5
  namespace: default
  name: test-listen-events
  version: 0.1.0
schedule:
  "on":
    one:
      with:
        type: com.abc.form.created.v1
do:
- setFooBar:
    set:
      foo: ${ $workflow.input}
```

### This happened:

The workflow got trigerred. But it is unable to fetch the input

![Image](https://github.com/user-attachments/assets/9bd27991-56b6-4586-83b0-a4e382503082)

### I expected this:

I expect to see the data in the input. 

### Is there a workaround?

NA

### Anything else?

Also, we are seeing this issue, where even when the workflow is updated to the next version, the instances of the workflow that are newly created are in the previous version and not the updated version

Eg, lets say, the workflow was updated from 0.1.0 to 0.1.1, instead of seeing the newly triggered worklfow in Instances section of 0.1.1, we see it in 0.1.0.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.name: Bug Report 🐞
