### ISSUE TITLE
Getting Started documentation is not helpful

### ISSUE THREAD

**Issue by LeifLazar** [serverlessworkflow/synapse#499]
I've been trying to setup Synapse locally, using Docker, on Windows 11 and ran into a couple of issues.
🟡 - Needs  documentation changes
🟢 - Needs to be added to documentation
🔴 - Might need code/configuration changes

🟡 Step 3 needs to be updated from:
`docker-compose build`
to:
`docker-compose -f docker-compose.build.yml build`

🟡 Step 4 needs to be updated from:
`docker-compose up`
to:
`docker-compose -f docker-compose.build.yml up`

🟢 Should add a mention that we need to pull a runner image to be able to run a workflow. For example:
`docker pull ghcr.io/serverlessworkflow/synapse/runner:1.0.0-alpha5`
🔴 I had to trick Synapse into running this `alpha5` image by running this command:
`docker tag ghcr.io/serverlessworkflow/synapse/runner:1.0.0-alpha5 ghcr.io/serverlessworkflow/synapse/runner:1.0.0`
What did I miss here?

🔴 I had to modify the `docker-compose.build.yml` file in two ways.
The `garnet` tag from:
```YAML
garnet:
  image: ghcr.io/microsoft/garnet
  volumes:
    - garnet_data:/data
```
to:
```YAML
garnet:
  image: ghcr.io/microsoft/garnet
  entrypoint:
    - /app/GarnetServer
    - --lua
  volumes:
    - garnet_data:/data
```
and in the `operator.environment` section I had to add this:
`SYNAPSE_RUNTIME_DOCKER_SECRETS_DIRECTORY: C:\Users\[MY_USER]\.synapse`

🟡 The example workflow definition needs to be updated from:
```YAML
# greeter.yaml
document:
  dsl: '1.0.0'
  name: greeter
  namespace: default
  version: '0.1.0'
do:
  greet:
    set:
      greetings: '${ "Hello \(.user.firstName) \(.user.lastName)!" }'
```
to:
```YAML
# greeter.yaml
document:
  dsl: "1.0.0-alpha5"
  name: greeter
  namespace: default
  version: "0.1.0"
do:
  - greet:
      set:
        greetings: ${ "Hello \(.user.firstName) \(.user.lastName)!" }
```
By this I mean that we need to make it more clear that the version can't just be copy-pasted (or actually solve that problem) and that the formatting of the `do...greet` is wrong.

🟡 We also need to mention that the version of the `dsl` property should match the version of the runner image that was pulled. Or at least that's what I thought. Am I wrong?
